services:
  mysql_db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mysql_db_data:/var/lib/mysql
      - ./web_event_app_dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome:115.0.5790.110
    env_file:
      - .env
    ports:
      - "${SELENIUM_PORT}:${SELENIUM_PORT}"
    networks:
      - app-network

  backend_service:
    build:
      context: ./backend
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    env_file:
      - ./backend/.env
    environment:
      - SPRING_DATASOURCE_URL=${MYSQL_URL}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql_db
      - selenium
    networks:
      - app-network

  frontend_service:
    build:
      context: ./frontend
    ports:
      - "${REACT_PORT}:${REACT_PORT}"
    env_file:
      - ./frontend/react-event-app/.env
    depends_on:
      - backend_service
    networks:
      - app-network

volumes:
  mysql_db_data:

networks:
  app-network:
    driver: bridge
